# 特定のファイルタイプで読み込む

[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
if = "has('nvim')"
on_i = 1
hook_source = '''
source ~/.config/nvim/plugins/deoplete.rc.vim
'''

# [[plugins]]
# repo = 'Shougo/neoyank.vim'
# on_if = 1
# on_event = 'TextYankPost'
# on_source = ['unite.vim', 'denite.nvim']

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'
on_source = ['unite.vim', 'vimshell.vim']

[[plugins]]
repo = 'Shougo/neosnippet'
hook_source = '''
  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_target)
'''
on_i  = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']

[[plugins]]
repo= 'jalvesaq/Nvim-R'
on_ft = ['rmd','r']
hook_source = '''
source ~/.config/nvim/plugins/Nvim-R.rc.vim
'''

[[plugins]]
repo = 'w0rp/ale'
on_ft = ['python']
hook_source = '''
"n-vim
nmap <silent> <C-w>j <Plug>(ale_next_wrap)
nmap <silent> <C-w>k <Plug>(ale_previous_wrap)
let g:ale_sign_column_always = 1
let g:ale_statusline_format = ['⨉ %d', '⚠ %d', '⬥ ok']
'''

[[plugins]]
repo = 'davidhalter/jedi'
on_ft = 'python'

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'
depends = ['deoplete.nvim','jedi']

[[plugins]]
repo = 'iamcco/mathjax-support-for-mkdp'
on_ft = ['markdown','mkd']

[[plugins]]
repo = 'iamcco/markdown-preview.vim'
depends = ['mathjax-support-for-mkdp']
on_ft = ['markdown','mkd']
hook_source = '''
let g:mkdp_path_to_chrome = "open -a Google\\ Chrome"
'''

[[plugins]]
repo = 'godlygeek/tabular'
on_ft = ['markdown','mkd']

[[plugins]]
repo = 'joker1007/vim-markdown-quote-syntax'
on_ft = ['markdown','mkd']

[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['markdown','mkd']

